baseURL = "https://lachlannwhitehill.com"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
theme = "hermit-v2"
enableRobotsTXT = true

[languages]
  [languages.en]
    title = 'Welcome'
    [languages.en.params]
      homeSubtitle = " to my little corner of the internet"
    weight = 1
 
languageCode = "en-us"

pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[taxonomies]
  tag = "tags"

# Enable to get proper Mathjax support
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      [markup.goldmark.extensions.passthrough]
#        enable = true
#        [markup.goldmark.extensions.passthrough.delimiters]
#          block = [['\[', '\]'], ['$$', '$$']]
#          inline = [['\(', '\)']]

[params]
  description = "A little corner of the internet just for my stuff"
  footerCopyright = "luper"
  footerHideThemeName = true
  justifyContent = false
  relatedPosts = true
  code_copy_button = true
  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = false
  shareSocial = false
  # denyRobots only for dev - will be set via build command
  usesAnimation = true
  # mathjaxLib = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
  # mermaidLib = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"
  
[params.gallery]
    enable = true
    thumbnail = '300'

[params.dateform]
    LongDate = "Jan 2, 2006"
    ShortDate = "Jan 2"
    NumDateShort = "2006-01-02"
    NumDateLong = "2006-01-02 15:04"

[[params.socialLinks]]
    name = "github"
    url = "https://github.com/luperr"

    [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/lwhitehill-884788247"

[menu]
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 20